export {
  SPRING_TRANSITION,
  STATIC_TRANSITION,
  MARQUEE_TITLE_TRANSITION,
  MARQUEE_INITIAL,
  MARQUEE_TITLE_ANIMATE,
  MARQUEE_TITLE_ANIMATE_STATIC,
  STATUS_FADE_TRANSITION,
  STATUS_TEXT_STROKE_STYLE,
  STATIC_OVERFLOW_MASK_STYLE,
} from "@/components/shared/lcd/lcdMotionConstants";
