/** Generated by scripts/compute-average-colors.ts — do not edit by hand. */

export const GAME_AVERAGE_COLORS: Record<string, string> = {
  "doom": "99,31,11",
  "simcity2000": "1,1,75",
  "mario": "59,126,165",
  "princeofpersia": "100,53,11",
  "aladdin": "150,86,0",
  "oregontrail": "2,127,169",
  "commandandconquer": "92,62,43",
  "atrain": "40,115,39",
  "simrefinery": "80,75,26",
};
