/** Generated by scripts/compute-average-colors.ts — do not edit by hand. */

export const GAME_AVERAGE_COLORS: Record<string, string> = {
  "doom": "56,33,25",
  "simcity2000": "34,25,37",
  "mario": "89,120,118",
  "princeofpersia": "68,45,45",
  "aladdin": "94,61,9",
  "oregontrail": "95,110,95",
  "commandandconquer": "81,60,48",
  "atrain": "82,113,66",
  "simrefinery": "73,69,58",
};
