import type { AppId } from "@/utils/i18n";

/**
 * i18n key suffix under `apps.<appId>.help.<suffix>` for each help carousel card index.
 * Must stay in sync with each app's exported `helpItems` array length and order.
 */
export const HELP_ITEM_KEYS_BY_APP_ID: Record<AppId, string[]> = {
  finder: [
    "browseNavigate",
    "fileManagement",
    "viewSort",
    "quickAccess",
    "storageInfo",
    "trash",
  ],
  soundboard: [
    "recordSlot",
    "keyboardPlay",
    "waveformView",
    "customizeSlot",
    "multipleBoards",
    "importExport",
  ],
  "internet-explorer": [
    "browseWeb",
    "travelThroughTime",
    "historyReimagined",
    "saveFavorites",
    "exploreTimeNodes",
    "shareJourney",
  ],
  chats: [
    "chatWithRyo",
    "createEditFiles",
    "controlApps",
    "joinChatRooms",
    "pushToTalk",
    "nudgeDjMode",
  ],
  textedit: [
    "richEditing",
    "formatting",
    "listsTasks",
    "fileManagement",
    "voiceDictation",
    "slashCommands",
  ],
  paint: ["drawingTools", "colors", "undo", "saving", "patterns", "filters"],
  "photo-booth": [
    "takingPhoto",
    "quickSnaps",
    "applyingEffects",
    "viewingPhotos",
    "downloadingPhotos",
    "switchingCameras",
  ],
  minesweeper: ["desktopControls", "mobileControls", "gameRules", "timerCounter", "restart"],
  videos: ["addVideo", "playback", "loop", "shuffle", "playlist", "retroUi"],
  tv: ["channels", "playback", "numbers", "shortcuts", "fullscreen", "helpAbout"],
  ipod: [
    "addSongs",
    "wheelNavigation",
    "playbackControls",
    "lyricsPronunciation",
    "playbackModes",
    "displayFullscreen",
  ],
  karaoke: [
    "addSearchSongs",
    "syncLyricsTiming",
    "stylePronunciation",
    "syncedWithIpod",
    "worksWithChats",
    "keyboardShortcuts",
  ],
  synth: [
    "virtualKeyboard",
    "controlsPanel",
    "presets",
    "waveform3d",
    "effects",
    "octaveShift",
  ],
  pc: ["pcEmulator", "keyboardControls", "mouseCapture", "fullscreenMode", "saveStates", "aspectRatio"],
  terminal: [
    "basicCommands",
    "navigation",
    "commandHistory",
    "aiAssistant",
    "fileEditing",
    "terminalSounds",
  ],
  "applet-viewer": [
    "appletStore",
    "createWithRyosChat",
    "viewApplets",
    "shareApplets",
    "openFromFinder",
    "keepUpdated",
  ],
  "control-panels": ["appearance", "sounds", "aiModel", "shaderEffects", "backupRestore", "sync", "system"],
  admin: ["adminAccess", "userManagement", "roomManagement", "statistics"],
  stickies: ["createNote", "colors", "moveResize", "deleteNote", "clearAll", "autoSave"],
  "infinite-mac": ["classicMacEmulator", "selectSystem", "pauseResume", "backToSystems"],
  winamp: ["playMusic", "equalizer", "playlist", "skins", "shuffleRepeat", "controls"],
  calendar: ["navigateMonths", "createEvents", "dayView", "colorCoding", "deleteEvents", "autoSave"],
  contacts: ["browseContacts", "createContacts", "editDetails", "importVCards", "useWithRyo", "cloudSync"],
  dashboard: ["openDashboard", "clockWidget", "calendarWidget", "weatherWidget", "moveWidgets", "closeDashboard"],
  candybar: ["browseIconPacks", "iconPackDetails", "applyIconPacks", "favorites", "search", "cloudLibrary"],
};
