/** Generated by scripts/compute-average-colors.ts — do not edit by hand. */

export const PRESET_AVERAGE_COLORS: Record<string, string> = {
  "kanjitalk-7-5": "148,148,169",
  "macos-8": "129,129,158",
  "macos-8-5": "107,107,143",
  "macos-9": "107,107,143",
  "macos-9-2": "64,64,106",
  "macosx-10-1": "34,64,116",
  "macosx-10-2": "19,43,91",
  "macosx-10-3": "17,37,78",
  "macosx-10-4": "39,74,117",
  "system-1": "94,94,94",
  "system-6": "95,95,95",
  "system-7-5": "148,148,169",
};
