/** Generated by scripts/compute-average-colors.ts — do not edit by hand. */

export const PRESET_AVERAGE_COLORS: Record<string, string> = {
  "kanjitalk-7-5": "117,125,152",
  "macos-8": "125,125,152",
  "macos-8-5": "70,70,109",
  "macos-9": "107,107,143",
  "macos-9-2": "69,69,109",
  "macosx-10-1": "35,64,116",
  "macosx-10-2": "21,47,94",
  "macosx-10-3": "17,37,78",
  "macosx-10-4": "20,43,92",
  "system-1": "94,94,94",
  "system-6": "95,95,95",
  "system-7-5": "130,130,131",
};
