/** Generated by scripts/compute-average-colors.ts — do not edit by hand. */

export const PRESET_AVERAGE_COLORS: Record<string, string> = {
  "kanjitalk-7-5": "128,128,129",
  "macos-8": "130,129,135",
  "macos-8-5": "123,123,130",
  "macos-9": "123,123,130",
  "macos-9-2": "90,89,110",
  "macosx-10-1": "105,115,131",
  "macosx-10-2": "99,111,128",
  "macosx-10-3": "92,103,118",
  "macosx-10-4": "104,113,126",
  "system-1": "82,82,82",
  "system-6": "82,82,82",
  "system-7-5": "128,128,129",
};
