/**
 * Generated from applelocalization's raw macOS 26.1 localization corpus.
 *
 * English keys are exact source-string matches. Localized values are the
 * dominant trimmed translations for ryOS's desktop locale variants.
 * Regenerate with `bun run i18n:apple-glossary`.
 */

export const APPLE_GLOSSARY_SOURCE = {
  "websiteRepository": "https://github.com/kishikawakatsumi/applelocalization-web",
  "dataRepository": "https://github.com/kishikawakatsumi/applelocalization-tools",
  "revision": "95fff5dfcf53ed5b849756865e8e5c4c327f9bc7",
  "tree": "e03797c80f73806faeec8ff16b666b1b74ba48d3",
  "path": "data/macos/26.1",
  "platform": "macOS",
  "version": "26.1"
} as const;

export const RAW_APPLE_UI_TERMINOLOGY = {
  "Settings": {
    "zh-TW": "設定",
    "zh-CN": "设置",
    "ja": "設定",
    "ko": "설정",
    "fr": "Réglages",
    "de": "Einstellungen",
    "es": "Ajustes",
    "pt": "Ajustes",
    "it": "Impostazioni",
    "ru": "Настройки"
  },
  "Trash": {
    "zh-TW": "垃圾桶",
    "zh-CN": "废纸篓",
    "ja": "ゴミ箱",
    "ko": "휴지통",
    "fr": "Corbeille",
    "de": "Papierkorb",
    "es": "Papelera",
    "pt": "Lixo",
    "it": "Cestino",
    "ru": "Корзина"
  },
  "Account": {
    "zh-TW": "帳號",
    "zh-CN": "账户",
    "ja": "アカウント",
    "ko": "계정",
    "fr": "Compte",
    "de": "Account",
    "es": "Cuenta",
    "pt": "Conta",
    "it": "Account",
    "ru": "Учетная запись"
  },
  "Log Out": {
    "zh-TW": "登出",
    "zh-CN": "退出登录",
    "ja": "ログアウト",
    "ko": "로그아웃",
    "fr": "Fermer la session",
    "de": "Abmelden",
    "es": "Cerrar sesión",
    "pt": "Finalizar Sessão",
    "it": "Logout",
    "ru": "Завершить сеанс"
  },
  "Sign In": {
    "zh-TW": "登入",
    "zh-CN": "登录",
    "ja": "サインイン",
    "ko": "로그인",
    "fr": "Se connecter",
    "de": "Anmelden",
    "es": "Iniciar sesión",
    "pt": "Iniciar Sessão",
    "it": "Accedi",
    "ru": "Войти"
  },
  "Sign Out": {
    "zh-TW": "登出",
    "zh-CN": "退出登录",
    "ja": "サインアウト",
    "ko": "로그아웃",
    "fr": "Déconnexion",
    "de": "Abmelden",
    "es": "Cerrar sesión",
    "pt": "Finalizar Sessão",
    "it": "Esci",
    "ru": "Выйти"
  },
  "Cancel": {
    "zh-TW": "取消",
    "zh-CN": "取消",
    "ja": "キャンセル",
    "ko": "취소",
    "fr": "Annuler",
    "de": "Abbrechen",
    "es": "Cancelar",
    "pt": "Cancelar",
    "it": "Annulla",
    "ru": "Отменить"
  },
  "Save": {
    "zh-TW": "儲存",
    "zh-CN": "保存",
    "ja": "保存",
    "ko": "저장",
    "fr": "Enregistrer",
    "de": "Sichern",
    "es": "Guardar",
    "pt": "Salvar",
    "it": "Salva",
    "ru": "Сохранить"
  },
  "Delete": {
    "zh-TW": "刪除",
    "zh-CN": "删除",
    "ja": "削除",
    "ko": "삭제",
    "fr": "Supprimer",
    "de": "Löschen",
    "es": "Eliminar",
    "pt": "Apagar",
    "it": "Elimina",
    "ru": "Удалить"
  },
  "Open": {
    "zh-TW": "打開",
    "zh-CN": "打开",
    "ja": "開く",
    "ko": "열기",
    "fr": "Ouvrir",
    "de": "Öffnen",
    "es": "Abrir",
    "pt": "Abrir",
    "it": "Apri",
    "ru": "Открыть"
  },
  "Close": {
    "zh-TW": "關閉",
    "zh-CN": "关闭",
    "ja": "閉じる",
    "ko": "닫기",
    "fr": "Fermer",
    "de": "Schließen",
    "es": "Cerrar",
    "pt": "Fechar",
    "it": "Chiudi",
    "ru": "Закрыть"
  },
  "New Window": {
    "zh-TW": "新增視窗",
    "zh-CN": "新建窗口",
    "ja": "新規ウインドウ",
    "ko": "새로운 윈도우",
    "fr": "Nouvelle fenêtre",
    "de": "Neues Fenster",
    "es": "Nueva ventana",
    "pt": "Nova Janela",
    "it": "Nuova finestra",
    "ru": "Новое окно"
  },
  "Full Screen": {
    "zh-TW": "全螢幕",
    "zh-CN": "全屏幕",
    "ja": "フルスクリーン",
    "ko": "전체 화면",
    "fr": "Plein écran",
    "de": "Vollbild",
    "es": "Pantalla completa",
    "pt": "Tela Cheia",
    "it": "A tutto schermo",
    "ru": "На весь экран"
  },
  "Help": {
    "zh-TW": "輔助說明",
    "zh-CN": "帮助",
    "ja": "ヘルプ",
    "ko": "도움말",
    "fr": "Aide",
    "de": "Hilfe",
    "es": "Ayuda",
    "pt": "Ajuda",
    "it": "Aiuto",
    "ru": "Справка"
  },
  "Calendar": {
    "zh-TW": "行事曆",
    "zh-CN": "日历",
    "ja": "カレンダー",
    "ko": "캘린더",
    "fr": "Calendrier",
    "de": "Kalender",
    "es": "Calendario",
    "pt": "Calendário",
    "it": "Calendario",
    "ru": "Календарь"
  },
  "Refresh": {
    "zh-TW": "重新整理",
    "zh-CN": "刷新",
    "ja": "更新",
    "ko": "새로 고침",
    "fr": "Actualiser",
    "de": "Aktualisieren",
    "es": "Actualizar",
    "pt": "Atualizar",
    "it": "Aggiorna",
    "ru": "Обновить"
  },
  "Videos": {
    "zh-TW": "影片",
    "zh-CN": "视频",
    "ja": "ビデオ",
    "ko": "비디오",
    "fr": "Vidéos",
    "de": "Videos",
    "es": "Vídeos",
    "pt": "Vídeos",
    "it": "Video",
    "ru": "Видео"
  },
  "Set Password": {
    "zh-TW": "設定密碼",
    "zh-CN": "设定密码",
    "ja": "パスワードを設定",
    "ko": "암호 설정",
    "fr": "Définir un mot de passe",
    "de": "Passwort festlegen",
    "es": "Definir contraseña",
    "pt": "Definir Senha",
    "it": "Imposta password",
    "ru": "Задать пароль"
  },
  "Contacts": {
    "zh-TW": "聯絡人",
    "zh-CN": "通讯录",
    "ja": "連絡先",
    "ko": "연락처",
    "fr": "Contacts",
    "de": "Kontakte",
    "es": "Contactos",
    "pt": "Contatos",
    "it": "Contatti",
    "ru": "Контакты"
  },
  "Green": {
    "zh-TW": "綠色",
    "zh-CN": "绿色",
    "ja": "グリーン",
    "ko": "초록색",
    "fr": "Vert",
    "de": "Grün",
    "es": "Verde",
    "pt": "Verde",
    "it": "Verde",
    "ru": "Зеленый"
  },
  "Blue": {
    "zh-TW": "藍色",
    "zh-CN": "蓝色",
    "ja": "ブルー",
    "ko": "파란색",
    "fr": "Bleu",
    "de": "Blau",
    "es": "Azul",
    "pt": "Azul",
    "it": "Blu",
    "ru": "Синий"
  },
  "Applications": {
    "zh-TW": "應用程式",
    "zh-CN": "应用程序",
    "ja": "アプリケーション",
    "ko": "응용 프로그램",
    "fr": "Applications",
    "de": "Apps",
    "es": "Aplicaciones",
    "pt": "Aplicativos",
    "it": "Applicazioni",
    "ru": "Приложения"
  },
  "Status": {
    "zh-TW": "狀態",
    "zh-CN": "状态",
    "ja": "状況",
    "ko": "상태",
    "fr": "État",
    "de": "Status",
    "es": "Estado",
    "pt": "Estado",
    "it": "Stato",
    "ru": "Статус"
  },
  "Yellow": {
    "zh-TW": "黃色",
    "zh-CN": "黄色",
    "ja": "イエロー",
    "ko": "노란색",
    "fr": "Jaune",
    "de": "Gelb",
    "es": "Amarillo",
    "pt": "Amarelo",
    "it": "Giallo",
    "ru": "Желтый"
  },
  "Folder": {
    "zh-TW": "檔案夾",
    "zh-CN": "文件夹",
    "ja": "フォルダ",
    "ko": "폴더",
    "fr": "Dossier",
    "de": "Ordner",
    "es": "Carpeta",
    "pt": "Pasta",
    "it": "Cartella",
    "ru": "Папка"
  },
  "Document": {
    "zh-TW": "文件",
    "zh-CN": "文稿",
    "ja": "書類",
    "ko": "문서",
    "fr": "Document",
    "de": "Dokument",
    "es": "Documento",
    "pt": "Documento",
    "it": "Documento",
    "ru": "Документ"
  },
  "Documents": {
    "zh-TW": "文件",
    "zh-CN": "文稿",
    "ja": "書類",
    "ko": "문서",
    "fr": "Documents",
    "de": "Dokumente",
    "es": "Documentos",
    "pt": "Documentos",
    "it": "Documenti",
    "ru": "Документы"
  },
  "Pink": {
    "zh-TW": "粉紅色",
    "zh-CN": "粉色",
    "ja": "ピンク",
    "ko": "분홍색",
    "fr": "Rose",
    "de": "Rosa",
    "es": "Rosa",
    "pt": "Rosa",
    "it": "Rosa",
    "ru": "Розовый"
  },
  "Songs": {
    "zh-TW": "歌曲",
    "zh-CN": "歌曲",
    "ja": "曲",
    "ko": "노래",
    "fr": "Morceaux",
    "de": "Titel",
    "es": "Canciones",
    "pt": "Músicas",
    "it": "Brani",
    "ru": "Песни"
  },
  "Screen Saver": {
    "zh-TW": "螢幕保護程式",
    "zh-CN": "屏幕保护程序",
    "ja": "スクリーンセーバ",
    "ko": "화면 보호기",
    "fr": "Économiseur d’écran",
    "de": "Bildschirmschoner",
    "es": "Salvapantallas",
    "pt": "Protetor de Tela",
    "it": "Salvaschermo",
    "ru": "Заставка"
  },
  "Numbered List": {
    "zh-TW": "編號列表",
    "zh-CN": "编号列表",
    "ja": "番号付きリスト",
    "ko": "번호 목록",
    "fr": "Liste numérotée",
    "de": "Nummerierte Liste",
    "es": "Lista numerada",
    "pt": "Lista Numerada",
    "it": "Elenco numerato",
    "ru": "Нумерованный список"
  },
  "Copy": {
    "zh-TW": "拷貝",
    "zh-CN": "拷贝",
    "ja": "コピー",
    "ko": "복사하기",
    "fr": "Copier",
    "de": "Kopieren",
    "es": "Copiar",
    "pt": "Copiar",
    "it": "Copia",
    "ru": "Скопировать"
  },
  "Speech": {
    "zh-TW": "語音",
    "zh-CN": "语音",
    "ja": "スピーチ",
    "ko": "말하기",
    "fr": "Parole",
    "de": "Sprachausgabe",
    "es": "Habla",
    "pt": "Fala",
    "it": "Voce",
    "ru": "Проговаривание текста"
  },
  "Add": {
    "zh-TW": "加入",
    "zh-CN": "添加",
    "ja": "追加",
    "ko": "추가",
    "fr": "Ajouter",
    "de": "Hinzufügen",
    "es": "Añadir",
    "pt": "Adicionar",
    "it": "Aggiungi",
    "ru": "Добавить"
  },
  "Password": {
    "zh-TW": "密碼",
    "zh-CN": "密码",
    "ja": "パスワード",
    "ko": "암호",
    "fr": "Mot de passe",
    "de": "Passwort",
    "es": "Contraseña",
    "pt": "Senha",
    "it": "Password",
    "ru": "Пароль"
  },
  "Bold": {
    "zh-TW": "粗體",
    "zh-CN": "粗体",
    "ja": "ボールド",
    "ko": "볼드체",
    "fr": "Gras",
    "de": "Fett",
    "es": "Negrita",
    "pt": "Negrito",
    "it": "Grassetto",
    "ru": "Жирный"
  },
  "Italic": {
    "zh-TW": "斜體",
    "zh-CN": "斜体",
    "ja": "イタリック",
    "ko": "이탤릭체",
    "fr": "Italique",
    "de": "Kursiv",
    "es": "Cursiva",
    "pt": "Itálico",
    "it": "Corsivo",
    "ru": "Курсив"
  },
  "Today": {
    "zh-TW": "今天",
    "zh-CN": "今天",
    "ja": "今日",
    "ko": "오늘",
    "fr": "Aujourd’hui",
    "de": "Heute",
    "es": "Hoy",
    "pt": "Hoje",
    "it": "Oggi",
    "ru": "Сегодня"
  },
  "Red": {
    "zh-TW": "紅色",
    "zh-CN": "红色",
    "ja": "レッド",
    "ko": "빨간색",
    "fr": "Rouge",
    "de": "Rot",
    "es": "Rojo",
    "pt": "Vermelho",
    "it": "Rosso",
    "ru": "Красный"
  },
  "Images": {
    "zh-TW": "影像",
    "zh-CN": "图像",
    "ja": "画像",
    "ko": "이미지",
    "fr": "Images",
    "de": "Bilder",
    "es": "Imágenes",
    "pt": "Imagens",
    "it": "Immagini",
    "ru": "Изображения"
  },
  "Desktop": {
    "zh-TW": "桌面",
    "zh-CN": "桌面",
    "ja": "デスクトップ",
    "ko": "데스크탑",
    "fr": "Bureau",
    "de": "Schreibtisch",
    "es": "Escritorio",
    "pt": "Mesa",
    "it": "Scrivania",
    "ru": "Рабочий стол"
  },
  "Move to Trash": {
    "zh-TW": "丟到垃圾桶",
    "zh-CN": "移到废纸篓",
    "ja": "ゴミ箱に入れる",
    "ko": "휴지통으로 이동",
    "fr": "Placer dans la corbeille",
    "de": "In den Papierkorb legen",
    "es": "Trasladar a la papelera",
    "pt": "Mover para o Lixo",
    "it": "Sposta nel Cestino",
    "ru": "Переместить в Корзину"
  },
  "User": {
    "zh-TW": "使用者",
    "zh-CN": "用户",
    "ja": "ユーザ",
    "ko": "사용자",
    "fr": "Utilisateur",
    "de": "Benutzer:in",
    "es": "Usuario",
    "pt": "Usuário",
    "it": "Utente",
    "ru": "Пользователь"
  },
  "Directions": {
    "zh-TW": "路線",
    "zh-CN": "路线",
    "ja": "経路",
    "ko": "경로",
    "fr": "Itinéraire",
    "de": "Route",
    "es": "Ruta",
    "pt": "Trajeto",
    "it": "Indicazioni",
    "ru": "Маршруты"
  },
  "Server": {
    "zh-TW": "伺服器",
    "zh-CN": "服务器",
    "ja": "サーバ",
    "ko": "서버",
    "fr": "Serveur",
    "de": "Server",
    "es": "Servidor",
    "pt": "Servidor",
    "it": "Server",
    "ru": "Сервер"
  },
  "Calculator": {
    "zh-TW": "計算機",
    "zh-CN": "计算器",
    "ja": "計算機",
    "ko": "계산기",
    "fr": "Calculatrice",
    "de": "Rechner",
    "es": "Calculadora",
    "pt": "Calculadora",
    "it": "Calcolatrice",
    "ru": "Калькулятор"
  },
  "Save Changes": {
    "zh-TW": "儲存所作更動",
    "zh-CN": "保存更改",
    "ja": "変更内容を保存",
    "ko": "변경 사항 저장",
    "fr": "Enregistrer les modifications",
    "de": "Änderungen sichern",
    "es": "Guardar cambios",
    "pt": "Salvar Alterações",
    "it": "Salva modifiche",
    "ru": "Сохранить"
  },
  "Services": {
    "zh-TW": "服務",
    "zh-CN": "服务",
    "ja": "サービス",
    "ko": "서비스",
    "fr": "Services",
    "de": "Dienste",
    "es": "Servicios",
    "pt": "Serviços",
    "it": "Servizi",
    "ru": "Службы"
  },
  "Cut": {
    "zh-TW": "剪下",
    "zh-CN": "剪切",
    "ja": "カット",
    "ko": "오려두기",
    "fr": "Couper",
    "de": "Ausschneiden",
    "es": "Cortar",
    "pt": "Cortar",
    "it": "Taglia",
    "ru": "Вырезать"
  },
  "Font": {
    "zh-TW": "字體",
    "zh-CN": "字体",
    "ja": "フォント",
    "ko": "서체",
    "fr": "Police",
    "de": "Schrift",
    "es": "Tipo de letra",
    "pt": "Fonte",
    "it": "Font",
    "ru": "Шрифт"
  },
  "Undo": {
    "zh-TW": "還原",
    "zh-CN": "撤销",
    "ja": "取り消す",
    "ko": "실행 취소",
    "fr": "Annuler",
    "de": "Widerrufen",
    "es": "Deshacer",
    "pt": "Desfazer",
    "it": "Annulla",
    "ru": "Отменить"
  },
  "Minimize": {
    "zh-TW": "縮到最小",
    "zh-CN": "最小化",
    "ja": "しまう",
    "ko": "최소화",
    "fr": "Minimiser",
    "de": "Minimieren",
    "es": "Minimizar",
    "pt": "Minimizar",
    "it": "Contrai",
    "ru": "Убрать в Dock"
  },
  "Show Colors": {
    "zh-TW": "顯示顏色",
    "zh-CN": "显示颜色",
    "ja": "カラーパネルを表示",
    "ko": "색상 보기",
    "fr": "Afficher les couleurs",
    "de": "Farben einblenden",
    "es": "Mostrar colores",
    "pt": "Mostrar Cores",
    "it": "Mostra colori",
    "ru": "Показать цвета"
  },
  "Quit": {
    "zh-TW": "結束",
    "zh-CN": "退出",
    "ja": "終了",
    "ko": "종료",
    "fr": "Quitter",
    "de": "Beenden",
    "es": "Salir",
    "pt": "Encerrar",
    "it": "Esci",
    "ru": "Завершить"
  },
  "Artist": {
    "zh-TW": "藝人",
    "zh-CN": "艺人",
    "ja": "アーティスト",
    "ko": "아티스트",
    "fr": "Artiste",
    "de": "Künstler:in",
    "es": "Artista",
    "pt": "Artista",
    "it": "Artista",
    "ru": "Артист"
  },
  "Action": {
    "zh-TW": "動作",
    "zh-CN": "操作",
    "ja": "アクション",
    "ko": "동작",
    "fr": "Action",
    "de": "Aktion",
    "es": "Acción",
    "pt": "Ação",
    "it": "Azione",
    "ru": "Действие"
  },
  "New Folder": {
    "zh-TW": "新增檔案夾",
    "zh-CN": "新建文件夹",
    "ja": "新規フォルダ",
    "ko": "새로운 폴더",
    "fr": "Nouveau dossier",
    "de": "Neuer Ordner",
    "es": "Nueva carpeta",
    "pt": "Nova Pasta",
    "it": "Nuova cartella",
    "ru": "Новая папка"
  },
  "Files": {
    "zh-TW": "檔案",
    "zh-CN": "文件",
    "ja": "ファイル",
    "ko": "파일",
    "fr": "Fichiers",
    "de": "Dateien",
    "es": "Archivos",
    "pt": "Arquivos",
    "it": "File",
    "ru": "Файлы"
  },
  "Show Sidebar": {
    "zh-TW": "顯示側邊欄",
    "zh-CN": "显示边栏",
    "ja": "サイドバーを表示",
    "ko": "사이드바 보기",
    "fr": "Afficher la barre latérale",
    "de": "Seitenleiste einblenden",
    "es": "Mostrar barra lateral",
    "pt": "Mostrar Barra Lateral",
    "it": "Mostra barra laterale",
    "ru": "Показать боковое меню"
  },
  "Downloads": {
    "zh-TW": "下載項目",
    "zh-CN": "下载",
    "ja": "ダウンロード",
    "ko": "다운로드",
    "fr": "Téléchargements",
    "de": "Downloads",
    "es": "Descargas",
    "pt": "Downloads",
    "it": "Download",
    "ru": "Загрузки"
  },
  "Artists": {
    "zh-TW": "藝人",
    "zh-CN": "艺人",
    "ja": "アーティスト",
    "ko": "아티스트",
    "fr": "Artistes",
    "de": "Künstler:innen",
    "es": "Artistas",
    "pt": "Artistas",
    "it": "Artisti",
    "ru": "Артисты"
  },
  "Playlists": {
    "zh-TW": "播放列表",
    "zh-CN": "播放列表",
    "ja": "プレイリスト",
    "ko": "플레이리스트",
    "fr": "Playlists",
    "de": "Playlists",
    "es": "Playlists",
    "pt": "Playlists",
    "it": "Playlist",
    "ru": "Плейлисты"
  },
  "Calendars": {
    "zh-TW": "行事曆",
    "zh-CN": "日历",
    "ja": "カレンダー",
    "ko": "캘린더",
    "fr": "Calendriers",
    "de": "Kalender",
    "es": "Calendarios",
    "pt": "Calendários",
    "it": "Calendari",
    "ru": "Календари"
  },
  "Song": {
    "zh-TW": "歌曲",
    "zh-CN": "歌曲",
    "ja": "曲",
    "ko": "노래",
    "fr": "Morceau",
    "de": "Titel",
    "es": "Canción",
    "pt": "Música",
    "it": "Brano",
    "ru": "Песня"
  },
  "Exit Full Screen": {
    "zh-TW": "離開全螢幕",
    "zh-CN": "退出全屏幕",
    "ja": "フルスクリーンを解除",
    "ko": "전체 화면 종료",
    "fr": "Quitter le mode plein écran",
    "de": "Vollbildmodus aus",
    "es": "Salir de pantalla completa",
    "pt": "Sair da Tela Cheia",
    "it": "Disattiva modalità a tutto schermo",
    "ru": "Выйти из полноэкранного режима"
  },
  "Actions": {
    "zh-TW": "動作",
    "zh-CN": "操作",
    "ja": "アクション",
    "ko": "동작",
    "fr": "Actions",
    "de": "Aktionen",
    "es": "Acciones",
    "pt": "Ações",
    "it": "Azioni",
    "ru": "Действия"
  },
  "TextEdit": {
    "zh-TW": "文字編輯",
    "zh-CN": "文本编辑",
    "ja": "テキストエディット",
    "ko": "텍스트 편집기",
    "fr": "TextEdit",
    "de": "TextEdit",
    "es": "TextEdit",
    "pt": "Editor de Texto",
    "it": "TextEdit",
    "ru": "TextEdit"
  },
  "Plain Text": {
    "zh-TW": "純文字",
    "zh-CN": "纯文本",
    "ja": "標準テキスト",
    "ko": "일반 텍스트",
    "fr": "Format texte",
    "de": "Reiner Text",
    "es": "Texto sin formato",
    "pt": "Texto Simples",
    "it": "Testo semplice",
    "ru": "Простой текст"
  },
  "Sidebar": {
    "zh-TW": "側邊欄",
    "zh-CN": "边栏",
    "ja": "サイドバー",
    "ko": "사이드바",
    "fr": "Barre latérale",
    "de": "Seitenleiste",
    "es": "Barra lateral",
    "pt": "Barra Lateral",
    "it": "Barra laterale",
    "ru": "Боковое меню"
  },
  "Restore": {
    "zh-TW": "回復",
    "zh-CN": "恢复",
    "ja": "復元",
    "ko": "복원",
    "fr": "Restaurer",
    "de": "Wiederherstellen",
    "es": "Restaurar",
    "pt": "Restaurar",
    "it": "Ripristina",
    "ru": "Восстановить"
  },
  "Stocks": {
    "zh-TW": "股市",
    "zh-CN": "股市",
    "ja": "株価",
    "ko": "주식",
    "fr": "Bourse",
    "de": "Aktien",
    "es": "Bolsa",
    "pt": "Bolsa",
    "it": "Borsa",
    "ru": "Акции"
  },
  "Empty Trash": {
    "zh-TW": "清空垃圾桶",
    "zh-CN": "清倒废纸篓",
    "ja": "ゴミ箱を空にする",
    "ko": "휴지통 비우기",
    "fr": "Vider la corbeille",
    "de": "Papierkorb entleeren",
    "es": "Vaciar papelera",
    "pt": "Esvaziar Lixo",
    "it": "Svuota il Cestino",
    "ru": "Очистить Корзину"
  },
  "Inches": {
    "zh-TW": "英寸",
    "zh-CN": "英寸",
    "ja": "インチ",
    "ko": "인치",
    "fr": "Pouces",
    "de": "Zoll",
    "es": "Pulgadas",
    "pt": "Polegadas",
    "it": "Pollici",
    "ru": "Дюймы"
  },
  "Centimeters": {
    "zh-TW": "公分",
    "zh-CN": "厘米",
    "ja": "センチメートル",
    "ko": "센티미터",
    "fr": "Centimètres",
    "de": "Zentimeter",
    "es": "Centímetros",
    "pt": "Centímetros",
    "it": "Centimetri",
    "ru": "Сантиметры"
  },
  "Speak": {
    "zh-TW": "朗讀",
    "zh-CN": "朗读",
    "ja": "読み上げ",
    "ko": "말하기",
    "fr": "Énoncer",
    "de": "Sprechen",
    "es": "Leer",
    "pt": "Falar",
    "it": "Leggi",
    "ru": "Произнести"
  },
  "Time Zone": {
    "zh-TW": "時區",
    "zh-CN": "时区",
    "ja": "時間帯",
    "ko": "시간대",
    "fr": "Fuseau horaire",
    "de": "Zeitzone",
    "es": "Zona horaria",
    "pt": "Fuso Horário",
    "it": "Fuso orario",
    "ru": "Часовой пояс"
  },
  "Rain": {
    "zh-TW": "下雨",
    "zh-CN": "下雨",
    "ja": "雨",
    "ko": "비",
    "fr": "Pluie",
    "de": "Regen",
    "es": "Lluvia",
    "pt": "Chuva",
    "it": "Pioggia",
    "ru": "Дождь"
  },
  "Added": {
    "zh-TW": "已加入",
    "zh-CN": "已添加",
    "ja": "追加済み",
    "ko": "추가됨",
    "fr": "Élément ajouté",
    "de": "Hinzugefügt",
    "es": "Añadido",
    "pt": "Adicionado",
    "it": "Aggiunta",
    "ru": "Добавлено"
  },
  "Next Page": {
    "zh-TW": "下一頁",
    "zh-CN": "下一页",
    "ja": "次のページ",
    "ko": "다음 페이지",
    "fr": "Page suivante",
    "de": "Nächste Seite",
    "es": "Página siguiente",
    "pt": "Página Seguinte",
    "it": "Pagina successiva",
    "ru": "Следующая страница"
  },
  "Delete Song": {
    "zh-TW": "刪除歌曲",
    "zh-CN": "删除歌曲",
    "ja": "曲を削除",
    "ko": "노래 삭제",
    "fr": "Supprimer le morceau",
    "de": "Titel löschen",
    "es": "Eliminar canción",
    "pt": "Apagar Música",
    "it": "Elimina brano",
    "ru": "Удалить песню"
  },
  "Markdown": {
    "zh-TW": "Markdown",
    "zh-CN": "Markdown",
    "ja": "マークダウン",
    "ko": "Markdown",
    "fr": "Markdown",
    "de": "Markdown",
    "es": "Markdown",
    "pt": "Markdown",
    "it": "Markdown",
    "ru": "Markdown"
  },
  "JPEG Image": {
    "zh-TW": "JPEG影像",
    "zh-CN": "JPEG图像",
    "ja": "JPEG画像",
    "ko": "JPEG 이미지",
    "fr": "Image JPEG",
    "de": "JPEG-Bild",
    "es": "Imagen JPEG",
    "pt": "Imagem JPEG",
    "it": "Immagine JPEG",
    "ru": "Изображение JPEG"
  },
  "PNG Image": {
    "zh-TW": "PNG影像",
    "zh-CN": "PNG图像",
    "ja": "PNG画像",
    "ko": "PNG 이미지",
    "fr": "Image PNG",
    "de": "PNG-Bild",
    "es": "Imagen PNG",
    "pt": "Imagem PNG",
    "it": "Immagine PNG",
    "ru": "Изображение PNG"
  },
  "Photo Booth": {
    "zh-TW": "Photo Booth",
    "zh-CN": "Photo Booth",
    "ja": "Photo Booth",
    "ko": "Photo Booth",
    "fr": "Photo Booth",
    "de": "Photo Booth",
    "es": "Photo Booth",
    "pt": "Photo Booth",
    "it": "Photo Booth",
    "ru": "Photo Booth"
  },
  "Degrees": {
    "zh-TW": "度數",
    "zh-CN": "度数",
    "ja": "ど",
    "ko": "각도",
    "fr": "Degrés",
    "de": "Grad",
    "es": "Grados",
    "pt": "Graus",
    "it": "Gradi",
    "ru": "Градусы"
  },
  "Graphite": {
    "zh-TW": "石墨色",
    "zh-CN": "石墨色",
    "ja": "グラファイト",
    "ko": "흑색",
    "fr": "Graphite",
    "de": "Graphit",
    "es": "Grafito",
    "pt": "Grafite",
    "it": "Grafite",
    "ru": "Графит"
  },
  "Humidity": {
    "zh-TW": "濕度",
    "zh-CN": "湿度",
    "ja": "湿度",
    "ko": "습도",
    "fr": "Humidité",
    "de": "Feuchtigkeit",
    "es": "Humedad",
    "pt": "Umidade",
    "it": "Umidità",
    "ru": "Влажность"
  },
  "Museum": {
    "zh-TW": "博物館",
    "zh-CN": "博物馆",
    "ja": "博物館/美術館",
    "ko": "박물관",
    "fr": "Musée",
    "de": "Museum",
    "es": "Museo",
    "pt": "Museu",
    "it": "Museo",
    "ru": "Музей"
  },
  "Play Music": {
    "zh-TW": "播放音樂",
    "zh-CN": "播放音乐",
    "ja": "ミュージックを再生",
    "ko": "음악 재생",
    "fr": "Lire la musique",
    "de": "Musik abspielen",
    "es": "Reproducir música",
    "pt": "Reproduzir Música",
    "it": "Riproduci musica",
    "ru": "Воспроизвести музыку"
  },
  "Zoo": {
    "zh-TW": "動物園",
    "zh-CN": "动物园",
    "ja": "動物園",
    "ko": "동물원",
    "fr": "Zoo",
    "de": "Zoo",
    "es": "Zoo",
    "pt": "Zoológico",
    "it": "Zoo",
    "ru": "Зоопарк"
  },
  "Add to Dock": {
    "zh-TW": "加入Dock中",
    "zh-CN": "添加到程序坞",
    "ja": "Dockに追加",
    "ko": "Dock에 추가",
    "fr": "Ajouter au Dock",
    "de": "Zum Dock hinzufügen",
    "es": "Añadir al Dock",
    "pt": "Adicionar ao Dock",
    "it": "Aggiungi al Dock",
    "ru": "Добавить в Dock"
  },
  "Email address": {
    "zh-TW": "電子郵件地址",
    "zh-CN": "电子邮件地址",
    "ja": "メールアドレス",
    "ko": "이메일 주소",
    "fr": "Adresse e-mail",
    "de": "E-Mail-Adresse",
    "es": "Dirección de correo electrónico",
    "pt": "Endereço de e‑mail",
    "it": "Indirizzo email",
    "ru": "Адрес e‑mail"
  },
  "OK": {
    "zh-TW": "好",
    "zh-CN": "好",
    "ja": "OK",
    "ko": "확인",
    "fr": "OK",
    "de": "OK",
    "es": "Aceptar",
    "pt": "OK",
    "it": "OK",
    "ru": "ОК"
  },
  "Application": {
    "zh-TW": "應用程式",
    "zh-CN": "应用程序",
    "ja": "アプリケーション",
    "ko": "응용 프로그램",
    "fr": "Application",
    "de": "App",
    "es": "Aplicación",
    "pt": "Aplicativo",
    "it": "Applicazione",
    "ru": "Программа"
  },
  "App": {
    "zh-TW": "App",
    "zh-CN": "App",
    "ja": "アプリ",
    "ko": "앱",
    "fr": "App",
    "de": "App",
    "es": "App",
    "pt": "App",
    "it": "App",
    "ru": "Приложение"
  }
} as const;
