/**
 * Computes per-image average RGB for Infinite Mac thumbnails and PC game images,
 * then writes generated TS modules used for card overlay and loading-placeholder backgrounds.
 *
 * Run: bun run generate:average-colors
 * Requires: ImageMagick (magick) on PATH
 */

import { readdirSync, writeFileSync, mkdirSync } from "fs";
import { join } from "path";
import { spawnSync } from "child_process";

const ROOT = join(import.meta.dir, "..");
const DEFAULT_RGB = "169,175,190";
/** Darken factor: 1 = unchanged, 0.6 = blend ~40% toward black. Light averages read better darkened. */
const DARKEN = 0.62;

// Game id → path relative to project root (public/...)
const GAME_IMAGE_PATHS: { id: string; path: string }[] = [
  { id: "doom", path: "public/assets/games/images/doom.webp" },
  { id: "simcity2000", path: "public/assets/games/images/simcity2000.webp" },
  { id: "mario", path: "public/assets/games/images/mario.webp" },
  { id: "princeofpersia", path: "public/assets/games/images/prince.webp" },
  { id: "aladdin", path: "public/assets/games/images/aladdin.webp" },
  { id: "oregontrail", path: "public/assets/games/images/oregon-trail.webp" },
  { id: "commandandconquer", path: "public/assets/games/images/command-conquer.webp" },
  { id: "atrain", path: "public/assets/games/images/a-train.webp" },
  { id: "simrefinery", path: "public/assets/games/images/simrefinery.webp" },
];

function computeAverageRgb(imagePath: string): string {
  const result = spawnSync(
    "magick",
    [
      imagePath,
      "-resize",
      "1x1!",
      "-format",
      "%[fx:int(255*r)],%[fx:int(255*g)],%[fx:int(255*b)]",
      "info:",
    ],
    { encoding: "utf8", cwd: ROOT }
  );
  if (result.error || result.status !== 0) {
    return DEFAULT_RGB;
  }
  const out = (result.stdout ?? "").trim();
  const m = /^(\d+),(\d+),(\d+)$/.exec(out);
  if (!m) return DEFAULT_RGB;
  const r = Math.round(Number(m[1]) * DARKEN);
  const g = Math.round(Number(m[2]) * DARKEN);
  const b = Math.round(Number(m[3]) * DARKEN);
  return `${r},${g},${b}`;
}

function main() {
  const presetDir = join(ROOT, "public/assets/infinite-mac-thumbnails");
  const presetEntries: [string, string][] = [];
  try {
    const files = readdirSync(presetDir);
    for (const f of files) {
      if (!f.endsWith(".png")) continue;
      const id = f.replace(/\.png$/, "");
      const path = join(presetDir, f);
      presetEntries.push([id, computeAverageRgb(path)]);
    }
  } catch (e) {
    console.warn("Preset thumbnails dir not found or unreadable:", presetDir, e);
  }

  const gameEntries: [string, string][] = GAME_IMAGE_PATHS.map(({ id, path }) => {
    const abs = join(ROOT, path);
    return [id, computeAverageRgb(abs)];
  });

  const presetLines = presetEntries
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([id, rgb]) => `  "${id}": "${rgb}",`)
    .join("\n");

  const gameLines = gameEntries
    .map(([id, rgb]) => `  "${id}": "${rgb}",`)
    .join("\n");

  const presetFile = `/** Generated by scripts/compute-average-colors.ts — do not edit by hand. */\n\nexport const PRESET_AVERAGE_COLORS: Record<string, string> = {\n${presetLines}\n};\n`;
  const gameFile = `/** Generated by scripts/compute-average-colors.ts — do not edit by hand. */\n\nexport const GAME_AVERAGE_COLORS: Record<string, string> = {\n${gameLines}\n};\n`;

  const presetOut = join(ROOT, "src/apps/infinite-mac/presetAverageColors.generated.ts");
  const gameOut = join(ROOT, "src/apps/pc/gameAverageColors.generated.ts");
  mkdirSync(join(ROOT, "src/apps/infinite-mac"), { recursive: true });
  mkdirSync(join(ROOT, "src/apps/pc"), { recursive: true });
  writeFileSync(presetOut, presetFile);
  writeFileSync(gameOut, gameFile);
  console.log("Wrote", presetOut, "and", gameOut);
}

main();
