#!/usr/bin/env bun
/**
 * Generate iOS PWA launch (splash) images and the matching
 * `<link rel="apple-touch-startup-image">` tags for index.html.
 *
 * iOS Safari does NOT use the web app manifest `background_color` for the
 * standalone launch screen. If a device has no startup image that matches its
 * exact resolution/orientation, iOS paints a plain WHITE screen during the
 * cold-start launch animation — which is what users see as a "blank flash"
 * when they switch back to a backgrounded home-screen PWA that iOS has killed.
 *
 * We render a solid-black canvas (matching the app's `#000` shell) with the
 * ryOS logo centered, for every supported device + orientation, and inject the
 * link tags into index.html between the IOS_SPLASH markers.
 *
 * Run with: `bun run scripts/generate-ios-splash.ts`
 */
import { mkdir, readFile, writeFile, rm } from "node:fs/promises";
import { join } from "node:path";
import sharp from "sharp";

const ROOT = process.cwd();
const SOURCE_LOGO = join(ROOT, "public/icons/mac-512.png");
const OUT_DIR = join(ROOT, "public/icons/splash");
const PUBLIC_OUT_PREFIX = "/icons/splash";
const INDEX_HTML = join(ROOT, "index.html");
const BACKGROUND = { r: 0, g: 0, b: 0, alpha: 1 };
// Logo occupies this fraction of the screen's shorter physical edge.
const LOGO_SCALE = 0.3;

const START_MARKER = "<!-- IOS_SPLASH_START (generated by scripts/generate-ios-splash.ts) -->";
const END_MARKER = "<!-- IOS_SPLASH_END -->";

interface Device {
  name: string;
  // Logical CSS points (portrait orientation) used in the media query.
  width: number;
  height: number;
  ratio: number;
}

// Logical (CSS point) sizes + device pixel ratios, portrait orientation.
// Covers iPhone 5/SE through iPhone 16 Pro Max and the current iPad lineup.
const DEVICES: Device[] = [
  { name: "iphone-5-se1", width: 320, height: 568, ratio: 2 },
  { name: "iphone-8-7-6s-6-se", width: 375, height: 667, ratio: 2 },
  { name: "iphone-plus", width: 414, height: 736, ratio: 3 },
  { name: "iphone-x-xs-11pro", width: 375, height: 812, ratio: 3 },
  { name: "iphone-xr-11", width: 414, height: 896, ratio: 2 },
  { name: "iphone-xsmax-11promax", width: 414, height: 896, ratio: 3 },
  { name: "iphone-12-13-mini", width: 360, height: 780, ratio: 3 },
  { name: "iphone-12-13-14", width: 390, height: 844, ratio: 3 },
  { name: "iphone-14plus-12-13-promax", width: 428, height: 926, ratio: 3 },
  { name: "iphone-14pro-15-15pro-16", width: 393, height: 852, ratio: 3 },
  { name: "iphone-14promax-15plus-15promax-16plus", width: 430, height: 932, ratio: 3 },
  { name: "iphone-16-pro", width: 402, height: 874, ratio: 3 },
  { name: "iphone-16-pro-max", width: 440, height: 956, ratio: 3 },
  { name: "ipad-9.7", width: 768, height: 1024, ratio: 2 },
  { name: "ipad-10.2", width: 810, height: 1080, ratio: 2 },
  { name: "ipad-10.9", width: 820, height: 1180, ratio: 2 },
  { name: "ipad-mini-8.3", width: 744, height: 1133, ratio: 2 },
  { name: "ipad-air-pro-10.5", width: 834, height: 1112, ratio: 2 },
  { name: "ipad-pro-11", width: 834, height: 1194, ratio: 2 },
  { name: "ipad-pro-12.9", width: 1024, height: 1366, ratio: 2 },
  { name: "ipad-pro-13-m4", width: 1032, height: 1376, ratio: 2 },
];

type Orientation = "portrait" | "landscape";

async function renderSplash(
  logo: Buffer,
  physW: number,
  physH: number,
  outPath: string
): Promise<void> {
  const logoSize = Math.round(Math.min(physW, physH) * LOGO_SCALE);
  const resizedLogo = await sharp(logo)
    .resize(logoSize, logoSize, { fit: "contain", background: { r: 0, g: 0, b: 0, alpha: 0 } })
    .png()
    .toBuffer();

  await sharp({
    create: { width: physW, height: physH, channels: 4, background: BACKGROUND },
  })
    .composite([{ input: resizedLogo, gravity: "center" }])
    // Palette-quantize: the canvas is almost entirely flat black with a small
    // centered logo, so an 8-bit palette PNG shrinks each image ~10x with no
    // visible difference on a launch screen.
    .png({ compressionLevel: 9, palette: true, quality: 90, effort: 10 })
    .toFile(outPath);
}

function fileName(device: Device, orientation: Orientation): string {
  return `${device.name}-${orientation}.png`;
}

function linkTag(device: Device, orientation: Orientation): string {
  // In landscape, device-width/height stay as Safari reports them per device;
  // the orientation media feature disambiguates which image to use.
  const media =
    `(device-width: ${device.width}px) and (device-height: ${device.height}px) ` +
    `and (-webkit-device-pixel-ratio: ${device.ratio}) and (orientation: ${orientation})`;
  return `    <link rel="apple-touch-startup-image" media="${media}" href="${PUBLIC_OUT_PREFIX}/${fileName(device, orientation)}" />`;
}

async function injectLinks(tags: string[]): Promise<void> {
  const html = await readFile(INDEX_HTML, "utf8");
  const block = `    ${START_MARKER}\n${tags.join("\n")}\n    ${END_MARKER}`;

  const startIdx = html.indexOf(START_MARKER);
  const endIdx = html.indexOf(END_MARKER);
  let next: string;
  if (startIdx !== -1 && endIdx !== -1) {
    next = html.slice(0, startIdx) + block + html.slice(endIdx + END_MARKER.length);
  } else {
    // Insert just before the manifest link as a sensible head location.
    const anchor = '    <link rel="manifest" href="/manifest.json" />';
    if (!html.includes(anchor)) {
      throw new Error("Could not find manifest link anchor in index.html");
    }
    next = html.replace(anchor, `${anchor}\n${block}`);
  }
  await writeFile(INDEX_HTML, next);
}

async function main() {
  await rm(OUT_DIR, { recursive: true, force: true });
  await mkdir(OUT_DIR, { recursive: true });
  const logo = await readFile(SOURCE_LOGO);

  const tags: string[] = [];
  for (const device of DEVICES) {
    for (const orientation of ["portrait", "landscape"] as Orientation[]) {
      const portraitW = device.width * device.ratio;
      const portraitH = device.height * device.ratio;
      const physW = orientation === "portrait" ? portraitW : portraitH;
      const physH = orientation === "portrait" ? portraitH : portraitW;
      const out = join(OUT_DIR, fileName(device, orientation));
      await renderSplash(logo, physW, physH, out);
      tags.push(linkTag(device, orientation));
      console.log(`[splash] ${fileName(device, orientation)} (${physW}x${physH})`);
    }
  }

  await injectLinks(tags);
  console.log(`[splash] Generated ${tags.length} images + injected link tags into index.html`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
